/* MAVLink2Lua - generated by mavgen_lua.py - DO NOT EDIT! */

#pragma once

#include <lua.hpp>

#include <mavlink_types.h>
#include <common/mavlink.h>

#include <map>

struct lua_State; // forward decl to remove dependency from lua.h

// prototype for pointer to parse_* functions
typedef void (*ParseFuncPtr)(lua_State*, const mavlink_message_t&);

// map of parse functions by message_id (24bit int with gaps in between)
extern std::map<int, ParseFuncPtr> funcmap;

// other functions providing access to MAVLink-related data/metadata
extern void provide_MavlinkStatus(lua_State* L, const mavlink_status_t& status);

